# Generated by Django 3.2.19 on 2023-05-18 23:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat_messages', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatparticipant',
            unique_together={('chat', 'user')},
        ),
    ]
